### ISSUE TITLE
Own Channel join

### ISSUE THREAD

**Issue by Koeseb** [d0p3t/SubNotifier#9]
Soo I got Affiliated the other day and i wanted to run the script also on my own channel koesebTV but everytime i try to start the script with joining my/his own channel it crashes.

soo the scrip is running on my own acc koesebTV and should join my channel #koesebTV
but somehow this doesn't work?

Error Message:

`15:06:08 - info: STARTING SubNotifier...
C:\Users\KönigS\Desktop\SubNotifier\node_modules\private\private.js:72
  for (var names = originalGetOPNs(object),
                   ^

TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (C:\Users\KönigS\Desktop\SubNotifier\node_mo
dules\private\private.js:72:20)
    at TwitchBot.Start (C:\Users\KönigS\Desktop\SubNotifier\src\lib/TwitchBot.js
:82:32)
    at Object.<anonymous> (C:\Users\KönigS\Desktop\SubNotifier\src/index.js:26:5
)
    at Module._compile (module.js:570:32)
    at loader (C:\Users\KönigS\Desktop\SubNotifier\node_modules\babel-register\l
ib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\KönigS\
Desktop\SubNotifier\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)`

**Comment by d0p3t** [comment]
**_Congratulations on Affiliate!_**

Have you setup messages in your configuration file for your own channel?

![bitmoji](https://render.bitstrips.com/v2/cpanel/b8b01acf-113e-4801-b09f-6403c66e3c4a-cca32a10-7ddb-429b-bc89-d32f09b447ae-v1.png?transparent=1&palette=1&width=246)

**Comment by Koeseb** [comment]
Thank you! :D

Yes i did setup a message for it.

**Comment by d0p3t** [comment]
Has this been fixed?

**Comment by d0p3t** [comment]
I could not replicate this issue

![screen shot 2018-06-20 at 13 58 10](https://user-images.githubusercontent.com/11293676/41675922-0d24aff6-7492-11e8-8aa1-29b3148d3d05.png)

Closing for now.
